function p = ff_cartpole(m1,l1,th1,dth1,ddth1,m2,l2,th2,dth2,ddth2,m3,l3,th3,dth3,ddth3,u_th1,u_th2,g)
%FF_CARTPOLE
%    P = FF_CARTPOLE(M1,L1,TH1,DTH1,DDTH1,M2,L2,TH2,DTH2,DDTH2,M3,L3,TH3,DTH3,DDTH3,U_TH1,U_TH2,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Nov-2016 10:04:59

t2 = th1+th2+th3;
t3 = cos(t2);
t4 = th1+th2;
t5 = sin(t2);
t6 = cos(t4);
t7 = l2.*t6;
t8 = l3.*t3;
t9 = sin(t4);
t10 = l2.*t9;
t11 = l3.*t5;
t12 = cos(th1);
t13 = l1.*t12;
t14 = t7+t8+t13;
t15 = sin(th1);
t16 = l1.*t15;
t17 = t10+t11+t16;
t18 = l3.*t3.*t17.*2.0;
t19 = t7+t8;
t20 = l3.*t5.*t19.*2.0;
t21 = t10+t11;
t22 = t7+t13;
t23 = t10+t16;
t24 = l3.*t3.*t21.*2.0;
t27 = l3.*t5.*t14.*2.0;
t25 = t18-t20+t24-t27;
t26 = m1.*t25.*(1.0./4.0);
t28 = l2.*t6.*t23.*4.0;
t38 = l2.*t9.*t22.*4.0;
t29 = t28-t38;
t30 = m1.*t29.*(1.0./4.0);
t31 = t14.*t21.*4.0;
t39 = t17.*t19.*4.0;
t32 = t31-t39;
t40 = m1.*t32.*(1.0./4.0);
t33 = t30-t40;
t34 = l3.*t5.*t14.*4.0;
t46 = l3.*t3.*t17.*4.0;
t35 = t34-t46;
t36 = t18+t20-t24-t27;
t37 = m1.*t36.*(1.0./4.0);
t41 = dth1.*t33;
t42 = l3.*t3.*t21.*4.0;
t45 = l3.*t5.*t19.*4.0;
t43 = t42-t45;
t44 = t26-t37;
p = [u_th1-dth1.*(dth2.*t33-dth3.*m1.*t35.*(1.0./4.0))-dth2.*(t41+dth3.*(t26+m1.*(t18+t20-l3.*t5.*t14.*2.0-l3.*t3.*t21.*2.0).*(1.0./4.0))+dth2.*(m1.*(l2.*t6.*t23.*2.0-l2.*t9.*t22.*2.0).*(1.0./2.0)-m1.*(t14.*t21.*2.0-t17.*t19.*2.0).*(1.0./2.0)))-dth3.*(dth2.*(t26+t37)-dth1.*m1.*t35.*(1.0./4.0)+dth3.*m1.*(t18-t27).*(1.0./2.0))-g.*m2.*t17-g.*m2.*t23-g.*l1.*m1.*t15;u_th2+dth1.*(t41-dth3.*t44)+dth3.*(dth1.*(t37-m1.*(t18-t20+t24-t27).*(1.0./4.0))-dth2.*m1.*t43.*(1.0./4.0)+dth3.*m1.*(t20-t24).*(1.0./2.0))-g.*m2.*t21-dth2.*dth3.*m1.*t43.*(1.0./4.0)-g.*l2.*m2.*t9;dth1.*(dth2.*t44-dth1.*m1.*t35.*(1.0./4.0))+dth2.*(dth1.*t44+dth2.*m1.*(t42-t45).*(1.0./4.0))-g.*l3.*m2.*t5];
