function p = M_cartpole(m1,l1,th1,dth1,ddth1,m2,l2,th2,dth2,ddth2,m3,l3,th3,dth3,ddth3,u_th1,u_th2,g)
%M_CARTPOLE
%    P = M_CARTPOLE(M1,L1,TH1,DTH1,DDTH1,M2,L2,TH2,DTH2,DDTH2,M3,L3,TH3,DTH3,DDTH3,U_TH1,U_TH2,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Nov-2016 10:05:00

t2 = cos(th1);
t3 = l1.^2;
t4 = sin(th1);
t6 = th1+th2;
t7 = th1+th2+th3;
t9 = cos(t6);
t10 = l2.*t9;
t11 = l1.*t2;
t17 = cos(t7);
t18 = l3.*t17;
t5 = t10+t11+t18;
t13 = sin(t6);
t14 = l2.*t13;
t15 = l1.*t4;
t19 = sin(t7);
t20 = l3.*t19;
t8 = t14+t15+t20;
t12 = t10+t11;
t16 = t14+t15;
t21 = l2.*t13.*t16.*2.0;
t22 = l2.*t9.*t12.*2.0;
t23 = t21+t22;
t24 = m1.*t23.*(1.0./2.0);
t25 = t10+t18;
t26 = t5.*t25.*2.0;
t27 = t14+t20;
t28 = t8.*t27.*2.0;
t29 = t26+t28;
t30 = m1.*t29.*(1.0./2.0);
t31 = t24+t30;
t32 = l2.^2;
t33 = l3.*t5.*t17.*2.0;
t34 = l3.*t8.*t19.*2.0;
t35 = t33+t34;
t36 = m1.*t35.*(1.0./2.0);
t37 = l3.*t17.*t25.*2.0;
t38 = l3.*t19.*t27.*2.0;
t39 = t37+t38;
t40 = m1.*t39.*(1.0./2.0);
t41 = l3.^2;
p = reshape([m1.*(t2.^2.*t3.*2.0+t3.*t4.^2.*2.0).*(1.0./2.0)+m1.*(t5.^2.*2.0+t8.^2.*2.0).*(1.0./2.0)+m1.*(t12.^2.*2.0+t16.^2.*2.0).*(1.0./2.0),t31,t36,t31,m1.*(t9.^2.*t32.*2.0+t13.^2.*t32.*2.0).*(1.0./2.0)+m1.*(t25.^2.*2.0+t27.^2.*2.0).*(1.0./2.0),t40,t36,t40,m1.*(t17.^2.*t41.*2.0+t19.^2.*t41.*2.0).*(1.0./2.0)],[3,3]);
