function p = PE_acrobat(m1,l1,th1,dth1,m2,l2,th2,dth2,m3,l3,th3,dth3,u_th1,u_th2,g)
%PE_ACROBAT
%    P = PE_ACROBAT(M1,L1,TH1,DTH1,M2,L2,TH2,DTH2,M3,L3,TH3,DTH3,U_TH1,U_TH2,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Nov-2016 11:57:40

t2 = cos(th1);
t3 = th1+th2;
t4 = cos(t3);
p = g.*m1.*(l1+l2+l3-l1.*t2.*(1.0./2.0))+g.*m3.*(l1+l2+l3-l1.*t2-l2.*t4-l3.*cos(th1+th2+th3).*(1.0./2.0))+g.*m2.*(l1+l2+l3-l1.*t2-l2.*t4.*(1.0./2.0));
