function p = PE_cartpole(m1,l1,th1,dth1,ddth1,m2,l2,th2,dth2,ddth2,m3,l3,th3,dth3,ddth3,u_th1,u_th2,g)
%PE_CARTPOLE
%    P = PE_CARTPOLE(M1,L1,TH1,DTH1,DDTH1,M2,L2,TH2,DTH2,DDTH2,M3,L3,TH3,DTH3,DDTH3,U_TH1,U_TH2,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Nov-2016 10:05:00

t2 = cos(th1);
t3 = th1+th2;
t4 = cos(t3);
p = g.*m1.*(l1+l2+l3-l1.*t2)+g.*m2.*(l1+l2+l3-l1.*t2-l2.*t4-l3.*cos(th1+th2+th3))+g.*m2.*(l1+l2+l3-l1.*t2-l2.*t4);
